import Image from 'next/image';
import Link from 'next/link';
import styles from './page.module.scss';
import ProductsGrid from './products/products-grid';

export const metadata = {
  title: {
    default: 'Home | Out of the Box',
    template: '%s | Out of the Box',
  },
  description: 'Generated by create next app',
};

export default function HomePage() {
  return (
    <div className={styles.pageWrapper}>
      <section className={styles.heroWrapper}>
        <Image
          src="/images/child-playing.png"
          alt="One year old child playing with wooden toys"
          fill
          priority
          style={{ objectFit: 'cover', zIndex: -1 }}
        />
        <div className={styles.heroContent}>
          <h1 className={styles.mainTitle}>
            Custom Toys, <br /> Crafted for Joy.
          </h1>
          <p className={styles.subTitle}>
            Unique, hand-made treasures for every imagination.
          </p>
          <Link className={styles.heroButton} href="/products">
            {' '}
            Browse the Shop
          </Link>
        </div>
      </section>

      <main>
        <ProductsGrid />
      </main>

      <footer className={styles.paymentSection}>
        <div className={styles.paymentContent}>
          <p>Secure Checkout</p>
          <div className={styles.paymentIcons}>
            {/* Use the Image component to set a fixed size */}
            <Image
              src="/images/visa.png"
              alt="Visa"
              width={40} // Sets the icon width
              height={25} // Sets the icon height
            />
            <Image
              src="/images/mastercard.webp"
              alt="Mastercard"
              width={35}
              height={25}
            />
            <Image
              src="/images/paypal.webp"
              alt="Paypal"
              width={30}
              height={30}
            />
            <Image
              src="/images/apple-pay.webp"
              alt="Apple Pay"
              width={30}
              height={25}
            />
          </div>
        </div>
      </footer>
    </div>
  );
}
